version: "3"

services:
    jsapplication:
        build: ./
        expose:
            - "5000"
        volumes:
            - "./:/app"
        env_file: .env
        command: gunicorn -b 0.0.0.0:5000 --reload app:app
        links:
            - jsdatabase

    jsdatabase:
        image: postgres:9.6
        volumes:
            - jsdb_data:/var/lib/postgresql
        expose:
            - "5432"

    webserver:
        build: ./nginx/
        ports:
            - "80:80"
            - "443:443"
        links:
            - jsapplication
        volumes:
            - "./app/static:/www/static"


volumes:
    jsdb_data:
        driver: local
