"""empty message

Revision ID: 75796e24f854
Revises: 651f5e60e39b
Create Date: 2019-01-20 17:07:14.953568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75796e24f854'
down_revision = '651f5e60e39b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('display_order', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('post_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_post_display_order'), 'post', ['display_order'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_display_order'), table_name='post')
    op.drop_column('post', 'post_type')
    op.drop_column('post', 'image')
    op.drop_column('post', 'display_order')
    # ### end Alembic commands ###
